"""Added user_id to Item model

Revision ID: 5f138164afdb
Revises: 57a65d1da9f7
Create Date: 2025-03-14 06:53:22.537953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f138164afdb'
down_revision = '57a65d1da9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_item_user', 'user', ['user_id'], ['id'])  # Named the foreign key constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_user', type_='foreignkey')  # Drop by name
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
