"""Add image_filename to Item

Revision ID: 679dd35d9bc7
Revises: 5f138164afdb
Create Date: 2025-03-15 13:39:20.532821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679dd35d9bc7'
down_revision = '5f138164afdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_item')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_found', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('time_found', sa.Time(), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('time_found')
        batch_op.drop_column('date_found')
        batch_op.drop_column('image_filename')

    op.create_table('report_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('location_found', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_found', sa.DATE(), nullable=False),
    sa.Column('time_found', sa.TIME(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
