"""Added returned field to Item model

Revision ID: a87f7dc45bf9
Revises: bbbb884dc597
Create Date: 2025-03-24 06:54:57.411472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87f7dc45bf9'
down_revision = 'bbbb884dc597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('returned')

    # ### end Alembic commands ###
